name: CI Pipeline

on:
  pull_request:
    branches: [ main, staging ]
  push:
    branches: [ feature/* ]

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push production images
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./docker/api/Dockerfile
        push: true
        tags: ${{ steps.meta-api.outputs.tags }}
        labels: ${{ steps.meta-api.outputs.labels }}
    
    - name: Deploy to production
      run: |
        echo "🚀 Déploiement en production"
        # Commandes de déploiement en production
        # kubectl apply -f k8s/production/
        # ou autre mécanisme de déploiement
    
    - name: Production smoke tests
      run: |
        sleep 60  # Attendre le démarrage complet
        
        # Tests de santé
        curl -f https://prod-api-url/health || exit 1
        
        # Test de prédiction
        response=$(curl -s -X POST https://prod-api-url/predict \
          -H "Content-Type: application/json" \
          -d '{"features": [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0]}')
        
        echo "Response: $response"
        
        # Vérifier que la réponse contient les champs attendus
        echo "$response" | jq -e '.prediction' || exit 1
        echo "$response" | jq -e '.confidence' || exit 1

